### PR TITLE
Update Cav Scout Roles

### PR DESCRIPTION
**Pull request by Robot-Panda15**
**When merged this pull request will:**
Update Cav Scout Strings, Updated Cav Scout Roles, etc

### CODE REVIEW

**Comment by Robot-Panda15** [comment]
hold for now, gotta update more stuff

**Comment by Robot-Panda15** [comment]
works with #102

**Comment by micahwhitsel** [comment]
Are these good to go?

**Comment by ColdEvul** [comment]
classname differ from parent classes.
It should also be inside of the news scout moduel

**Pull request closed without merging**
