### PR TITLE
Add Charlie Weapons Units

### LINKED ISSUE #102: Classnames to add
Charlie Weapons Loadouts

- [x] Cav_B_C_MMGTeamLead_F
- [x] Cav_B_C_MMGGunner_F
- [x] Cav_B_C_MMGAssistant_F
- [x] Cav_B_C_SLMTeamLead_F
- [x] Cav_B_C_SLMGunner_F
- [x] Cav_B_C_SLMAmmoBearer_F

Bravo Cav Scouts

- [x] Cav_B_B_Driver_F
- [x] Cav_B_B_Gunner_F
- [x] Cav_B_B_Scout_PlatoonLeader_F
- [x] Cav_B_B_Scout_PlatoonSergeant_F
- [x] Cav_B_B_Scout_SquadLead_F
- [x] Cav_B_B_Scout_AutomaticRifleman_F
- [x] Cav_B_B_Scout_Grenadier_F
- [x] Cav_B_B_Scout_CombatLifeSaver_F

Name Changes
- [x] Cav_B_B_Scout_Driver_F name changed from Driver to Scout Driver
- [x] Cav_B_B_Scout_Gunner_F name changed from Gunner to Scout Gunner

### PR DESCRIPTION
**Pull request by Robot-Panda15**
Fixes and closes #102

### CODE REVIEW

**Comment by micahwhitsel** [comment]
@ColdEvul What's happening with this?

**Comment by ColdEvul** [comment]
It was redesigned and integrated to my knowledge.

**Comment by micahwhitsel** [comment]
> It was redesigned and integrated to my knowledge.

Alright, then it just seems to compositions would still need updating for them to actually be utilized @Robot-Panda15

**Comment by ColdEvul** [comment]
if its not in we can reopen it but to my knowlage i redesigned it

**Pull request closed without merging**
